Repository Decide-Single-Falla/decide-single-falla, pull requests merged in 2023-12, with the labels that each got.

#21 feature: CI/CD
  .github/workflows/django.yml
  decide/local_settings.example.py
  decide/voting/discord_t.py
  decide/voting/migrations/0005_voting_private.py
  requirements.txt
Labels: feature

#33 Fix workflow triggers
  .github/workflows/django.yml
Labels: bug

#45 Testing for feature 8: Decide API GETs
  decide/census/tests.py
  decide/census/views.py
  decide/voting/tests.py
Labels: testing

#50 Loadtest for private voting
  loadtest/locustfile.py
Labels: testing

#57 Feature: 56 configure pr label checker and add in gactions
  .github/pr-title-checker-config.json
  .github/workflows/django.yml
Labels: CI

#60 Feature: 59 implementing test to increment coverage
  decide/authentication/tests.py
  decide/booth/tests.py
  decide/voting/tests.py
  loadtest/gen_census.py
  loadtest/locustfile.py
Labels: testing

#63 Feature: new CICD test
  .github/workflows/django.yml
Labels: CI

#55 Feature: #53 decide discord post voting integration
  decide/authentication/urls.py
  decide/authentication/views.py
  discord/bot.py
  discord/utils/formatter.py
  requirements.txt
Labels: feature

#64 Feature: #61 discord bot extension testing
  .github/workflows/django.yml
  .gitignore
  decide/voting/discord_vote_t.py
  discord/bot.py
  discord/test/discord_help_t.py
  discord/test/test_utils/help.py
  discord/test/test_utils/switch.py
  discord/utils/__init__.py
Labels: testing

#70 Release 1.0.0
  .github/pr-title-checker-config.json
  .github/workflows/django.yml
  .gitignore
  README.md
  decide/authentication/tests.py
  decide/authentication/urls.py
  decide/authentication/views.py
  decide/booth/tests.py
  decide/census/tests.py
  decide/census/views.py
  decide/visualizer/tests.py
  decide/voting/discord_failed_t.py
  decide/voting/discord_t.py
  decide/voting/discord_vote_t.py
  decide/voting/tests.py
  discord/bot.py
  discord/requirements.txt
  discord/test/discord_help_t.py
  discord/test/test_utils/help.py
  discord/test/test_utils/switch.py
  discord/utils/__init__.py
  discord/utils/formatter.py
  docker/Dockerfile
  docker/docker-compose.yml
  docker/docker-settings.py
  loadtest/gen_census.py
  loadtest/locustfile.py
  requirements.txt
Labels: feature

#72 Feature: Changed color button
  decide/booth/templates/booth/booth.html
Labels: feature

#73 Fix: M3 button change
  decide/booth/templates/booth/booth.html
Labels: feature
